development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: TrueHeroes_development
  pool: 5
  username: johncapecelatro
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: TrueHeroes_test
  pool: 5
  username: johncapecelatro
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: TrueHeroes_production
  pool: 5
  username: johncapecelatro
  password:
